version: 2
updates:
  - package-ecosystem: "pip"  # ใช้ pip เพราะเป็น Python/Jupyter Notebook
    directory: "/"
    schedule:
      interval: "weekly"
    # ตั้งค่าจำกัดจำนวน PR ต่อครั้ง เพื่อไม่ให้รกเกินไป
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      
